name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # 매일 실행
  workflow_dispatch:
  push:
    branches:
      - main  # master 대신 main 브랜치 사용

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Generate Snake
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: minzzzun
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GH_TOKEN 대신 GITHUB_TOKEN 사용
